# Generated by Django 5.0.6 on 2025-02-27 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_level_user_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestimage',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.request'),
        ),
    ]
