# Generated by Django 5.0.6 on 2025-02-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_requestimage_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='closed',
            field=models.DateTimeField(null=True),
        ),
    ]
