# Generated by Django 5.0.6 on 2025-02-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_request_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='rank',
            field=models.IntegerField(unique=True),
        ),
    ]
