# Generated by Django 5.0.6 on 2025-03-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_tier_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='email_contact',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='phone_contact',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
